name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

      - name: Build and push Docker image
        run: |
          docker build -t gift-app .
          docker tag gift-app arsb29/gift-app:latest
          docker login -u arsb29 -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push arsb29/gift-app:latest

      - name: Deploy to remote server & Set up SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/gift-app
            git pull origin main
            docker login -u arsb29 -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker-compose down && \
            docker pull arsb29/gift-app:latest && \
            docker-compose up api-prod -d 
